method: bayes
metric:
  name: rouge_1_f_score
  goal: maximize
parameters:
  method:
    value:
      clause-summary-matching
#      sentence-complement
  summary:
    value: openai
  embedding:
    value: openai
  abridge-threshold:
    value: 0.1
  length-penalty:
    min: .0001
    max: .2
    distribution: log_uniform_values
